version: "3.8"

services:
  app:
    build: .
    container_name: go-marketplace-app
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/cmd

  db:
    image: mysql:8.0
    container_name: go-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fullstack_marketplace_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
